import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import Footer from "@/components/shared/Footer";
import AiChatAssistant from "@/components/shared/AiChatAssistant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AgorVision Ai",
  description: "Generated by create next app",
};

import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col bg-white dark:bg-gray-950">
        <ThemeProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer/>
          <AiChatAssistant />
        </ThemeProvider>
      </body>
    </html>
  );
}
